### PR TITLE
v0.12.0

### PR DESCRIPTION
**Pull request by stolarczyk**
to do
- [x] wait for https://github.com/databio/yacman/pull/52

### CODE REVIEW

**Comment by stolarczyk** [comment]
@nsheff are you planning any updates to the looper plugin?

**Comment by nsheff** [comment]
I think yes I'm not quite finished with it. Will try to get it done by Thursday. it will only be small tweaks

**Comment by nsheff** [comment]
should this be 0.12.0?

**Comment by stolarczyk** [comment]
good call, we added some features

**Pull request merged**
