### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by nsheff**
Are we approaching a release of 0.11.0?

### CODE REVIEW

**Comment by nsheff** [comment]
I bring this up because it's required for some refgenie plugin stuff I'm using in other projects.

**Comment by stolarczyk** [comment]
Yes, I think that all the planned features are implemented in every refgenie system component. I meant to open the PRs soon

**Comment by stolarczyk** [comment]
@nsheff, once you approve we can start the release process of the whole refgenie system.

Things to look at are specified in the changelog for [v0.11.0]( https://github.com/refgenie/refgenconf/blob/dev/docs/changelog.md#0110---unreleased)

**Comment by nsheff** [comment]
Do we need to document the looper refgenie plugin?

**Comment by stolarczyk** [comment]
do you mean briefly describe looper plugin system or just include the the function in the API docs? 

https://github.com/refgenie/refgenconf/blob/7cedfb9d919a68d0d866c39227c62a5bb12447dc/refgenconf/populator.py#L14-L25

I thought it was included in the API docs, but it isn't

**Comment by nsheff** [comment]
I was actually thinking a brief tutorial on how to use that plugin would be useful.

**Comment by nsheff** [comment]
I guess such a tutorial would belong in refgenie anyway since that's where the docs are.

This looks good to me. Go ahead and release when you're ready.

**Pull request merged**
